### ISSUE TITLE
Error: Unexpected close tag

### ISSUE THREAD

**Issue by Antonyboc** [bradenmacdonald/ofx-js#2]
Hello we have this error since 1-3 month.

the file is ok, le console log of the file after read is ok but  OFXParser.parse(text) fail with this error 

Uncaught (in promise) Error: Unexpected close tag
Line: 0
Column: 420
Char: >
    at error (sax.js:667:1)
    at strictFail (sax.js:693:1)
    at closeTag (sax.js:887:1)
    at SAXParser.write (sax.js:1449:1)
    at ./node_modules/ofx-js/node_modules/xml2js/lib/parser.js.exports.Parser.Parser.parseString (parser.js:323:1)
    at Parser.parseString (parser.js:5:48)
    at ofx.js:20:1
    at new Promise (<anonymous>)
    at parseXml (ofx.js:19:1)
    at ofx.js:55:1
    
Can you help me please ?

**Comment by bradenmacdonald** [comment]
I'll need more details to be able to diagnose the issue. In particular, I'd need to see the OFX file. Could you please manually edit the file down to the smallest valid version that gives the error? **Be very careful to remove or randomize/replace any financial, account, and/or personal information that is in the file before sharing.**

**Comment by Antonyboc** [comment]
`OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE
<OFX>
<SIGNONMSGSRSV1>
<SONRS>
<STATUS>
<CODE>0
<SEVERITY>INFO
</STATUS>
<DTSERVER>*******
<LANGUAGE>FRA
<DTPROFUP>******
<DTACCTUP>******
</SONRS>
</SIGNONMSGSRSV1>
<BANKMSGSRSV1>
<STMTTRNRS>
<TRNUID>******
<STATUS>
<CODE>0
<SEVERITY>INFO
</STATUS>
<STMTRS>
<CURDEF>EUR
<BANKACCTFROM>
<BANKID>*****</BANKID>
<BRANCHID>*****</BRANCHID>
<ACCTID>*****</ACCTID>
<ACCTTYPE>CHECKING</ACCTTYPE>
</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>****
<DTEND>****
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-45.54
<FITID>******
<CHECKNUM>*****
<NAME>FRAIS DE TUTELLE
<MEMO>*******
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>******
<TRNAMT>-90.00
<FITID>*****
<CHECKNUM>****
<NAME>ACHAT PRODUITS HYGIENE
<MEMO>******
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-78.73
<FITID>*****
<CHECKNUM>*****
<NAME>APIVIA COURTAGE
<MEMO>********
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>*****
<TRNAMT>+721.01
<FITID>*****
<CHECKNUM>*****
<NAME>EURO VIR CARSAT LANGUEDOC ROUSSI
<MEMO>******
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>****
<TRNAMT>+130.83
<FITID>******
<CHECKNUM>*****
<NAME>EURO VIR CARSAT TI LR PREST
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>*****
<TRNAMT>+247.28
<FITID>****
<CHECKNUM>******
<NAME>EURO VIR CAF GARD
<MEMO>******
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-37.00
<FITID>*****
<CHECKNUM>*****
<NAME>DIRECTION GENERALE DES
<MEMO>******
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-122.00
<FITID>****
<CHECKNUM>*****
<NAME>CHEQUE
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>***
<TRNAMT>-448.00
<FITID>****
<CHECKNUM>***
<NAME>DIRECTION GENERALE DES
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>***
<TRNAMT>-2199.50
<FITID>****
<CHECKNUM>*****
<NAME>EHPAD 092023
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-3.00
<FITID>****
<CHECKNUM>****
<NAME>COTISATIONS BANCAIRES
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>*****
<TRNAMT>-21.41
<FITID>*****
<CHECKNUM>***
<NAME>DDFIP GARD
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>***
<TRNAMT>-44.50
<FITID>****
<CHECKNUM>****
<NAME>COTISATIONS BANCAIRES
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>****
<TRNAMT>+23947.61
<FITID>****
<CHECKNUM>****
<NAME>VIR
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-45.54
<FITID>****
<CHECKNUM>****
<NAME>FRAIS DE TUTELLE
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-122.00
<FITID>****
<CHECKNUM>*****
<NAME>CHEQUE
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>*****
<TRNAMT>-78.73
<FITID>*****
<CHECKNUM>****
<NAME>APIVIA COURTAGE
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>****
<TRNAMT>+721.01
<FITID>*****
<CHECKNUM>****
<NAME>EURO VIR CARSAT LANGUEDOC ROUSSI
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>*****
<TRNAMT>+130.83
<FITID>****
<CHECKNUM>*****
<NAME>EURO VIR CARSAT TI LR PREST
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>*****
<TRNAMT>+242.28
<FITID>*****
<CHECKNUM>*****
<NAME>EURO VIR CAF GARD
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-3.00
<FITID>****
<CHECKNUM>*****
<NAME>COTISATIONS BANCAIRES
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-2267.65
<FITID>****
<CHECKNUM>****
<NAME>****
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>*****
<TRNAMT>-78.73
<FITID>****
<CHECKNUM>****
<NAME>****
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>***
<TRNAMT>+637.88
<FITID>****
<CHECKNUM>****
<NAME>EURO VIR CARSAT LANGUEDOC ROUSSI
<MEMO>EURO ****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>****
<TRNAMT>+130.83
<FITID>****
<CHECKNUM>****
<NAME>EURO VIR CARSAT TI LR PREST
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>***
<TRNAMT>+242.28
<FITID>****
<CHECKNUM>*****
<NAME>EURO VIR CAF GARD
<MEMO>*****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>***
<TRNAMT>-45.54
<FITID>****
<CHECKNUM>****
<NAME>FRAIS DE TUTELLE
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>****
<TRNAMT>-3.00
<FITID>***
<CHECKNUM>****
<NAME>COTISATIONS BANCAIRES
<MEMO>****
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>***
<TRNAMT>-122.00
<FITID>***
<CHECKNUM>****
<NAME>SNC L ESCALE 30ST PRIVAT DES
<MEMO>*****
</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL>
<BALAMT>+23757.44
<DTASOF>****
</LEDGERBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`

hello i anonimyzed with "*" .

Thank you for your help

**Comment by n4gava** [comment]
I'm having the same issue. Some banks don't close the tag; it seems to be outside the standard, but I've encountered two banks with the same situation.

![image](https://github.com/bradenmacdonald/ofx-js/assets/6059249/824d8bda-282f-4e01-9039-8969e1a17e6f)

**Comment by bradenmacdonald** [comment]
@Antonyboc I think this might fix it: https://github.com/bradenmacdonald/ofx-js/pull/3
Can you please test?

Also, this repo doesn't have much of a test suite, so I'd appreciate any help in testing that the fix doesn't introduce other regressions.

@n4gava The screenshot you provided is the SGML variant which this code does already handle, but it does so in a very simplistic way by using a few regular expressions to convert the SGML to XML. I can't say what the issue is from your screenshot, but let me know if the fix linked above solves it for you or not.

**Comment by bradenmacdonald** [comment]
A new version `0.2.0` has been published on NPM that includes the fix.
