### ISSUE TITLE
Incorrect Variable Assignment in Documentation

### ISSUE THREAD

**Issue by unt34** [bradenmacdonald/ofx-js#4]
I noticed an error in the documentation of the project. In the documentation section related to variable assignment, there is a mistake in the code snippet provided. The variable `currencyCode` is assigned twice, which seems to be a typo.

**Actual:**
`const currencyCode = currencyCode = statementResponse.CURDEF;`

**Should be:**
`const currencyCode = statementResponse.CURDEF;`

**Comment by bradenmacdonald** [comment]
Whoops :p Fixed! Thanks for letting me know.
